version: '3'
services:
  ridnvil:
    build: .
    container_name: ridnvil-dev-web
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`ridnvil.dev`)"
      - "traefik.http.services.web.loadbalancer.server.port=3001"