version: '3.8'

services:
  ridnvildb:
    image: mariadb:latest
    container_name: ridnvil-dev-db
    environment:
      MARIADB_ROOT_PASSWORD: v5jd7Sk61lL99Yumna
    ports:
      - "3002:3306"
    networks:
      - ridnvil-net

  ridnvil:
    build: .
    container_name: ridnvil-dev-web
    ports:
      - "3001:3001"
    environment:
      - HOST=root:v5jd7Sk61lL99Yumna@tcp(127.0.0.1:3306)/ridnvil?charset=utf8mb4&parseTime=True&loc=Local
      - HOST_ONLY=root:v5jd7Sk61lL99Yumna@tcp(127.0.0.1:3306)/?charset=utf8mb4&parseTime=True&loc=Local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`ridnvil.dev`)"
      - "traefik.http.services.web.loadbalancer.server.port=3001"
    restart: always
    networks:
      - public
      - ridnvil-net

networks:
  public:
    external: true
  ridnvil-net:
    driver: bridge